fn main() {
    relm4_icons_build::bundle_icons(
        "icon_names.rs",
        Some("dev.maciz.sessionschronicle"),
        None::<&str>,
        None::<&str>,
        [
            "graph",
            "prohibited-regular",
            "error-circle-regular",
            "text-snippet",
            "edit-document",
            "terminal",
            "search",
            "smart-toy",
            "earth",
            "build",
        ],
    );
}
