use crate::icon_names;
use crate::models::TokenUsage;
use crate::models::ToolCallStatus;

/// Format a millisecond duration as a human-readable string.
///
/// - `< 1 s`  → `"Nms"`
/// - `< 1 min` → `"N.Ns"`
/// - `≥ 1 min` → `"Nm Ns"`
pub fn format_duration_ms(ms: i64) -> String {
    if ms < 1_000 {
        format!("{}ms", ms)
    } else if ms < 60_000 {
        format!("{:.1}s", ms as f64 / 1_000.0)
    } else {
        let secs = ms / 1_000;
        format!("{}m {}s", secs / 60, secs % 60)
    }
}

/// Icon name for a tool-call status, suitable for `gtk::Image::from_icon_name`.
pub fn status_icon_name(status: ToolCallStatus) -> &'static str {
    match status {
        ToolCallStatus::Completed => "emblem-ok-symbolic",
        ToolCallStatus::Error => "dialog-error-symbolic",
        ToolCallStatus::Running => "emblem-synchronizing-symbolic",
        ToolCallStatus::Pending => "content-loading-symbolic",
        ToolCallStatus::Unknown => "dialog-question-symbolic",
    }
}

/// Short human-readable label for a tool-call status.
pub fn tool_status_label(status: ToolCallStatus) -> &'static str {
    match status {
        ToolCallStatus::Pending => "pending",
        ToolCallStatus::Running => "running",
        ToolCallStatus::Completed => "done",
        ToolCallStatus::Error => "error",
        ToolCallStatus::Unknown => "unknown",
    }
}

/// CSS class for a tool-call status badge.
pub fn tool_status_css_class(status: ToolCallStatus) -> &'static str {
    match status {
        ToolCallStatus::Completed => "status-completed",
        ToolCallStatus::Error => "status-error",
        ToolCallStatus::Running => "status-running",
        ToolCallStatus::Pending => "status-pending",
        ToolCallStatus::Unknown => "status-unknown",
    }
}

/// Format an integer with thin-space (U+2009) thousands grouping: 12 345 678
pub fn format_token_count(n: i64) -> String {
    let negative = n < 0;
    let abs = n.unsigned_abs();
    let digits = abs.to_string();
    let mut result = String::with_capacity(digits.len() + digits.len() / 3);
    for (i, ch) in digits.chars().enumerate() {
        if i > 0 && (digits.len() - i).is_multiple_of(3) {
            result.push('\u{2009}');
        }
        result.push(ch);
    }
    if negative {
        format!("-{}", result)
    } else {
        result
    }
}

/// Build the token details line: "12 345 input · 678 output [· 456 reasoning]"
#[allow(dead_code)]
pub fn format_token_details(usage: &TokenUsage) -> String {
    let mut parts = vec![
        format!("{} input", format_token_count(usage.input_tokens)),
        format!("{} output", format_token_count(usage.output_tokens)),
    ];
    if let Some(reasoning) = usage.reasoning_tokens {
        parts.push(format!("{} reasoning", format_token_count(reasoning)));
    }
    parts.join(" \u{00b7} ")
}

/// Build the cache line: "9 012 read [· 234 write]", or None if no cache data.
pub fn format_token_cache(usage: &TokenUsage) -> Option<String> {
    let mut parts = Vec::new();
    if let Some(read) = usage.cache_read_tokens {
        parts.push(format!("{} read", format_token_count(read)));
    }
    if let Some(write) = usage.cache_write_tokens {
        parts.push(format!("{} write", format_token_count(write)));
    }
    if parts.is_empty() {
        None
    } else {
        Some(parts.join(" \u{00b7} "))
    }
}

/// Build analytics primary summary: "12 345 input / 678 output / 13 023 total".
pub fn format_analytics_token_primary(input_tokens: i64, output_tokens: i64) -> String {
    let total = input_tokens + output_tokens;
    format!(
        "{} input / {} output / {} total",
        format_token_count(input_tokens),
        format_token_count(output_tokens),
        format_token_count(total)
    )
}

/// Build analytics secondary summary for optional cache/reasoning data.
pub fn format_analytics_token_secondary(
    cache_read_tokens: Option<i64>,
    cache_write_tokens: Option<i64>,
    reasoning_tokens: Option<i64>,
) -> Option<String> {
    let mut parts = Vec::new();

    let mut cache_parts = Vec::new();
    if let Some(read) = cache_read_tokens {
        cache_parts.push(format!("{} read", format_token_count(read)));
    }
    if let Some(write) = cache_write_tokens {
        cache_parts.push(format!("{} write", format_token_count(write)));
    }
    if !cache_parts.is_empty() {
        parts.push(format!("cache: {}", cache_parts.join(" \u{00b7} ")));
    }

    if let Some(reasoning) = reasoning_tokens {
        parts.push(format!("reasoning: {}", format_token_count(reasoning)));
    }

    if parts.is_empty() {
        None
    } else {
        Some(parts.join(" \u{00b7} "))
    }
}

/// Explanatory tooltip for the token details line.
#[allow(dead_code)]
pub fn token_details_tooltip(usage: &TokenUsage) -> String {
    let mut lines = vec![
        "Input: tokens sent to the model (prompt + context)".to_string(),
        "Output: tokens generated by the model".to_string(),
    ];
    if usage.reasoning_tokens.is_some() {
        lines.push("Reasoning: extra reasoning tokens when the assistant reports them".to_string());
    }
    lines.join("\n")
}

/// Explanatory tooltip for the cache line.
#[allow(dead_code)]
pub fn token_cache_tooltip() -> &'static str {
    "Read: tokens served from prompt cache\n\
     Write: tokens stored in prompt cache for future requests\n\
     Depending on provider, cache tokens may overlap with input tokens"
}

/// Concise token semantics help text for analytics and detail views.
pub fn token_semantics_help_tooltip() -> &'static str {
    "Input: tokens sent to the model\n\
     Output: tokens generated by the model\n\
     Reasoning: extra reasoning tokens when the assistant reports them\n\
     Cache: cache activity; depending on provider, cache tokens may overlap with input tokens"
}

/// Return the dominant tool-call activity using the design precedence:
/// edits > commands > reads. Returns `None` when no tool calls exist.
pub fn format_dominant_activity(
    edit_count: usize,
    command_count: usize,
    read_count: usize,
) -> Option<String> {
    if edit_count > 0 {
        Some(format_count(edit_count, "edit", "edits"))
    } else if command_count > 0 {
        Some(format_count(command_count, "command", "commands"))
    } else if read_count > 0 {
        Some(format_count(read_count, "read", "reads"))
    } else {
        None
    }
}

/// Format a count with explicit singular and plural words.
pub fn format_count(count: usize, singular: &str, plural: &str) -> String {
    if count == 1 {
        format!("1 {singular}")
    } else {
        format!("{count} {plural}")
    }
}

pub fn format_session_duration(
    start: chrono::DateTime<chrono::Utc>,
    end: chrono::DateTime<chrono::Utc>,
) -> String {
    let total_minutes = end.signed_duration_since(start).num_minutes().max(0);
    let hours = total_minutes / 60;
    let minutes = total_minutes % 60;

    if hours > 0 {
        format!("{hours}h {minutes}m")
    } else {
        format!("{total_minutes}m")
    }
}

pub fn format_ending_label(status: &crate::models::SessionEndingStatus) -> &'static str {
    match status {
        crate::models::SessionEndingStatus::Clean => "Ended cleanly",
        crate::models::SessionEndingStatus::Abrupt => "Ended unexpectedly",
        crate::models::SessionEndingStatus::Error => "Ended with error",
        crate::models::SessionEndingStatus::Unknown => "Ending unknown",
    }
}

pub fn format_ending_accessible_label(status: &crate::models::SessionEndingStatus) -> &'static str {
    match status {
        crate::models::SessionEndingStatus::Clean => "Session ended cleanly",
        crate::models::SessionEndingStatus::Abrupt => "Session ended unexpectedly",
        crate::models::SessionEndingStatus::Error => "Session ended with error",
        crate::models::SessionEndingStatus::Unknown => "Session ending status unknown",
    }
}

/// Icon name for a session ending badge.
pub fn ending_icon_name(status: &crate::models::SessionEndingStatus) -> Option<&'static str> {
    match status {
        crate::models::SessionEndingStatus::Abrupt => Some(icon_names::PROHIBITED_REGULAR),
        crate::models::SessionEndingStatus::Error => Some(icon_names::ERROR_CIRCLE_REGULAR),
        _ => None,
    }
}

/// Tooltip text for a session ending badge.
pub fn ending_tooltip(status: &crate::models::SessionEndingStatus) -> Option<&'static str> {
    match status {
        crate::models::SessionEndingStatus::Abrupt => {
            Some("Session ended unexpectedly before completion")
        }
        crate::models::SessionEndingStatus::Error => Some("Session ended because of an error"),
        _ => None,
    }
}

/// CSS class for a session ending label.
pub fn ending_css_class(status: &crate::models::SessionEndingStatus) -> &'static str {
    match status {
        crate::models::SessionEndingStatus::Clean => "ending-clean",
        crate::models::SessionEndingStatus::Abrupt => "ending-interrupted",
        crate::models::SessionEndingStatus::Error => "ending-failed",
        crate::models::SessionEndingStatus::Unknown => "ending-unknown",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::TokenUsage;

    #[test]
    fn format_token_count_zero() {
        assert_eq!(format_token_count(0), "0");
    }

    #[test]
    fn format_token_count_under_thousand() {
        assert_eq!(format_token_count(999), "999");
    }

    #[test]
    fn format_token_count_thousands() {
        assert_eq!(format_token_count(1000), "1\u{2009}000");
        assert_eq!(format_token_count(12345), "12\u{2009}345");
    }

    #[test]
    fn format_token_count_millions() {
        assert_eq!(format_token_count(1234567), "1\u{2009}234\u{2009}567");
    }

    #[test]
    fn format_token_count_negative() {
        assert_eq!(format_token_count(-1234), "-1\u{2009}234");
    }

    #[test]
    fn format_token_details_input_output_only() {
        let usage = TokenUsage {
            input_tokens: 12345,
            output_tokens: 678,
            cache_read_tokens: None,
            cache_write_tokens: None,
            reasoning_tokens: None,
        };
        assert_eq!(
            format_token_details(&usage),
            "12\u{2009}345 input \u{00b7} 678 output"
        );
    }

    #[test]
    fn format_token_details_with_reasoning() {
        let usage = TokenUsage {
            input_tokens: 12345,
            output_tokens: 678,
            cache_read_tokens: None,
            cache_write_tokens: None,
            reasoning_tokens: Some(456),
        };
        assert_eq!(
            format_token_details(&usage),
            "12\u{2009}345 input \u{00b7} 678 output \u{00b7} 456 reasoning"
        );
    }

    #[test]
    fn format_token_cache_both() {
        let usage = TokenUsage {
            input_tokens: 0,
            output_tokens: 0,
            cache_read_tokens: Some(9012),
            cache_write_tokens: Some(234),
            reasoning_tokens: None,
        };
        assert_eq!(
            format_token_cache(&usage),
            Some("9\u{2009}012 read \u{00b7} 234 write".to_string())
        );
    }

    #[test]
    fn format_token_cache_read_only() {
        let usage = TokenUsage {
            input_tokens: 0,
            output_tokens: 0,
            cache_read_tokens: Some(200),
            cache_write_tokens: None,
            reasoning_tokens: None,
        };
        assert_eq!(format_token_cache(&usage), Some("200 read".to_string()));
    }

    #[test]
    fn format_token_cache_none() {
        let usage = TokenUsage {
            input_tokens: 100,
            output_tokens: 50,
            cache_read_tokens: None,
            cache_write_tokens: None,
            reasoning_tokens: None,
        };
        assert_eq!(format_token_cache(&usage), None);
    }

    #[test]
    fn token_details_tooltip_without_reasoning() {
        let usage = TokenUsage {
            input_tokens: 100,
            output_tokens: 50,
            cache_read_tokens: None,
            cache_write_tokens: None,
            reasoning_tokens: None,
        };
        let tooltip = token_details_tooltip(&usage);
        assert!(tooltip.contains("Input:"));
        assert!(tooltip.contains("Output:"));
        assert!(!tooltip.contains("Reasoning:"));
    }

    #[test]
    fn token_details_tooltip_with_reasoning() {
        let usage = TokenUsage {
            input_tokens: 100,
            output_tokens: 50,
            cache_read_tokens: None,
            cache_write_tokens: None,
            reasoning_tokens: Some(30),
        };
        let tooltip = token_details_tooltip(&usage);
        assert!(tooltip.contains("Reasoning:"));
    }

    #[test]
    fn format_analytics_token_primary_formats_input_output_total() {
        assert_eq!(
            format_analytics_token_primary(12345, 678),
            "12\u{2009}345 input / 678 output / 13\u{2009}023 total"
        );
    }

    #[test]
    fn format_analytics_token_secondary_returns_none_without_optional_data() {
        assert_eq!(format_analytics_token_secondary(None, None, None), None,);
    }

    #[test]
    fn format_analytics_token_secondary_supports_cache_and_reasoning() {
        assert_eq!(
            format_analytics_token_secondary(Some(9012), Some(234), Some(56)),
            Some("cache: 9\u{2009}012 read \u{00b7} 234 write \u{00b7} reasoning: 56".to_string()),
        );
    }

    #[test]
    fn token_semantics_help_mentions_provider_overlap() {
        let tooltip = token_semantics_help_tooltip();
        assert!(tooltip.contains("Input:"));
        assert!(tooltip.contains("Output:"));
        assert!(tooltip.contains("Reasoning:"));
        assert!(tooltip.contains("cache"));
        assert!(tooltip.contains("provider"));
        assert!(tooltip.contains("overlap"));
    }

    #[test]
    fn token_cache_tooltip_mentions_possible_overlap_with_input() {
        let tooltip = token_cache_tooltip();
        assert!(tooltip.contains("cache"));
        assert!(tooltip.contains("input"));
        assert!(tooltip.contains("overlap"));
    }

    #[test]
    fn format_count_uses_singular_and_plural_forms() {
        assert_eq!(format_count(0, "message", "messages"), "0 messages");
        assert_eq!(format_count(1, "message", "messages"), "1 message");
        assert_eq!(format_count(2, "message", "messages"), "2 messages");
    }

    #[test]
    fn format_dominant_activity_edits_first() {
        assert_eq!(format_dominant_activity(3, 2, 1), Some("3 edits".into()));
        assert_eq!(format_dominant_activity(1, 2, 1), Some("1 edit".into()));
    }

    #[test]
    fn format_dominant_activity_commands_when_no_edits() {
        assert_eq!(format_dominant_activity(0, 5, 3), Some("5 commands".into()));
        assert_eq!(format_dominant_activity(0, 1, 3), Some("1 command".into()));
    }

    #[test]
    fn format_dominant_activity_reads_when_no_edits_or_commands() {
        assert_eq!(format_dominant_activity(0, 0, 4), Some("4 reads".into()));
        assert_eq!(format_dominant_activity(0, 0, 1), Some("1 read".into()));
    }

    #[test]
    fn format_dominant_activity_none_when_no_tool_calls() {
        assert_eq!(format_dominant_activity(0, 0, 0), None);
    }

    #[test]
    fn ending_css_class_maps_status_to_class() {
        assert_eq!(
            ending_css_class(&crate::models::SessionEndingStatus::Clean),
            "ending-clean"
        );
        assert_eq!(
            ending_css_class(&crate::models::SessionEndingStatus::Abrupt),
            "ending-interrupted"
        );
        assert_eq!(
            ending_css_class(&crate::models::SessionEndingStatus::Error),
            "ending-failed"
        );
        assert_eq!(
            ending_css_class(&crate::models::SessionEndingStatus::Unknown),
            ""
        );
    }

    #[test]
    fn ending_icon_name_maps_status_to_icon() {
        assert_eq!(
            ending_icon_name(&crate::models::SessionEndingStatus::Clean),
            None
        );
        assert_eq!(
            ending_icon_name(&crate::models::SessionEndingStatus::Abrupt),
            Some(icon_names::PROHIBITED_REGULAR)
        );
        assert_eq!(
            ending_icon_name(&crate::models::SessionEndingStatus::Error),
            Some(icon_names::ERROR_CIRCLE_REGULAR)
        );
        assert_eq!(
            ending_icon_name(&crate::models::SessionEndingStatus::Unknown),
            None
        );
    }

    #[test]
    fn ending_tooltip_maps_status_to_clear_description() {
        assert_eq!(
            ending_tooltip(&crate::models::SessionEndingStatus::Clean),
            None
        );
        assert_eq!(
            ending_tooltip(&crate::models::SessionEndingStatus::Abrupt),
            Some("Session ended unexpectedly before completion")
        );
        assert_eq!(
            ending_tooltip(&crate::models::SessionEndingStatus::Error),
            Some("Session ended because of an error")
        );
        assert_eq!(
            ending_tooltip(&crate::models::SessionEndingStatus::Unknown),
            None
        );
    }

    #[test]
    fn format_session_duration_shows_hours_and_minutes() {
        use chrono::{TimeZone, Utc};

        let start = Utc.with_ymd_and_hms(2026, 3, 30, 10, 0, 0).unwrap();
        let end = Utc.with_ymd_and_hms(2026, 3, 30, 12, 14, 0).unwrap();

        assert_eq!(format_session_duration(start, end), "2h 14m");
    }

    #[test]
    fn format_session_duration_clamps_negative_ranges_to_zero_minutes() {
        use chrono::{TimeZone, Utc};

        let start = Utc.with_ymd_and_hms(2026, 3, 30, 10, 0, 0).unwrap();
        let end = Utc.with_ymd_and_hms(2026, 3, 30, 9, 59, 0).unwrap();

        assert_eq!(format_session_duration(start, end), "0m");
    }

    #[test]
    fn format_ending_label_covers_all_statuses() {
        use crate::models::SessionEndingStatus;

        assert_eq!(
            format_ending_label(&SessionEndingStatus::Clean),
            "Ended cleanly"
        );
        assert_eq!(
            format_ending_label(&SessionEndingStatus::Abrupt),
            "Ended unexpectedly"
        );
        assert_eq!(
            format_ending_label(&SessionEndingStatus::Error),
            "Ended with error"
        );
        assert_eq!(
            format_ending_label(&SessionEndingStatus::Unknown),
            "Ending unknown"
        );
    }

    #[test]
    fn format_ending_accessible_label_covers_all_statuses() {
        use crate::models::SessionEndingStatus;

        assert_eq!(
            format_ending_accessible_label(&SessionEndingStatus::Clean),
            "Session ended cleanly"
        );
        assert_eq!(
            format_ending_accessible_label(&SessionEndingStatus::Abrupt),
            "Session ended unexpectedly"
        );
        assert_eq!(
            format_ending_accessible_label(&SessionEndingStatus::Error),
            "Session ended with error"
        );
        assert_eq!(
            format_ending_accessible_label(&SessionEndingStatus::Unknown),
            "Session ending status unknown"
        );
    }
}
