use crate::models::TokenUsage;
use crate::models::ToolCallStatus;

/// Format a millisecond duration as a human-readable string.
///
/// - `< 1 s`  → `"Nms"`
/// - `< 1 min` → `"N.Ns"`
/// - `≥ 1 min` → `"Nm Ns"`
pub fn format_duration_ms(ms: i64) -> String {
    if ms < 1_000 {
        format!("{}ms", ms)
    } else if ms < 60_000 {
        format!("{:.1}s", ms as f64 / 1_000.0)
    } else {
        let secs = ms / 1_000;
        format!("{}m {}s", secs / 60, secs % 60)
    }
}

/// Icon name for a tool-call status, suitable for `gtk::Image::from_icon_name`.
pub fn status_icon_name(status: ToolCallStatus) -> &'static str {
    match status {
        ToolCallStatus::Completed => "emblem-ok-symbolic",
        ToolCallStatus::Error => "dialog-error-symbolic",
        ToolCallStatus::Running => "emblem-synchronizing-symbolic",
        ToolCallStatus::Pending => "content-loading-symbolic",
        ToolCallStatus::Unknown => "dialog-question-symbolic",
    }
}

/// Short human-readable label for a tool-call status.
pub fn tool_status_label(status: ToolCallStatus) -> &'static str {
    match status {
        ToolCallStatus::Pending => "pending",
        ToolCallStatus::Running => "running",
        ToolCallStatus::Completed => "done",
        ToolCallStatus::Error => "error",
        ToolCallStatus::Unknown => "unknown",
    }
}

/// CSS class for a tool-call status badge.
pub fn tool_status_css_class(status: ToolCallStatus) -> &'static str {
    match status {
        ToolCallStatus::Completed => "status-completed",
        ToolCallStatus::Error => "status-error",
        ToolCallStatus::Running => "status-running",
        ToolCallStatus::Pending => "status-pending",
        ToolCallStatus::Unknown => "status-unknown",
    }
}

/// Format an integer with thin-space (U+2009) thousands grouping: 12 345 678
pub fn format_token_count(n: i64) -> String {
    let negative = n < 0;
    let abs = n.unsigned_abs();
    let digits = abs.to_string();
    let mut result = String::with_capacity(digits.len() + digits.len() / 3);
    for (i, ch) in digits.chars().enumerate() {
        if i > 0 && (digits.len() - i).is_multiple_of(3) {
            result.push('\u{2009}');
        }
        result.push(ch);
    }
    if negative {
        format!("-{}", result)
    } else {
        result
    }
}

/// Build the token details line: "12 345 input · 678 output [· 456 reasoning]"
pub fn format_token_details(usage: &TokenUsage) -> String {
    let mut parts = vec![
        format!("{} input", format_token_count(usage.input_tokens)),
        format!("{} output", format_token_count(usage.output_tokens)),
    ];
    if let Some(reasoning) = usage.reasoning_tokens {
        parts.push(format!("{} reasoning", format_token_count(reasoning)));
    }
    parts.join(" \u{00b7} ")
}

/// Build the cache line: "9 012 read [· 234 write]", or None if no cache data.
pub fn format_token_cache(usage: &TokenUsage) -> Option<String> {
    let mut parts = Vec::new();
    if let Some(read) = usage.cache_read_tokens {
        parts.push(format!("{} read", format_token_count(read)));
    }
    if let Some(write) = usage.cache_write_tokens {
        parts.push(format!("{} write", format_token_count(write)));
    }
    if parts.is_empty() {
        None
    } else {
        Some(parts.join(" \u{00b7} "))
    }
}

/// Build analytics primary summary: "12 345 input / 678 output / 13 023 total".
pub fn format_analytics_token_primary(input_tokens: i64, output_tokens: i64) -> String {
    let total = input_tokens + output_tokens;
    format!(
        "{} input / {} output / {} total",
        format_token_count(input_tokens),
        format_token_count(output_tokens),
        format_token_count(total)
    )
}

/// Build analytics secondary summary for optional cache/reasoning data.
pub fn format_analytics_token_secondary(
    cache_read_tokens: Option<i64>,
    cache_write_tokens: Option<i64>,
    reasoning_tokens: Option<i64>,
) -> Option<String> {
    let mut parts = Vec::new();

    let mut cache_parts = Vec::new();
    if let Some(read) = cache_read_tokens {
        cache_parts.push(format!("{} read", format_token_count(read)));
    }
    if let Some(write) = cache_write_tokens {
        cache_parts.push(format!("{} write", format_token_count(write)));
    }
    if !cache_parts.is_empty() {
        parts.push(format!("cache: {}", cache_parts.join(" \u{00b7} ")));
    }

    if let Some(reasoning) = reasoning_tokens {
        parts.push(format!("reasoning: {}", format_token_count(reasoning)));
    }

    if parts.is_empty() {
        None
    } else {
        Some(parts.join(" \u{00b7} "))
    }
}

/// Explanatory tooltip for the token details line.
pub fn token_details_tooltip(usage: &TokenUsage) -> String {
    let mut lines = vec![
        "Input: tokens sent to the model (prompt + context)".to_string(),
        "Output: tokens generated by the model".to_string(),
    ];
    if usage.reasoning_tokens.is_some() {
        lines.push("Reasoning: extra reasoning tokens when the assistant reports them".to_string());
    }
    lines.join("\n")
}

/// Explanatory tooltip for the cache line.
pub fn token_cache_tooltip() -> &'static str {
    "Read: tokens served from prompt cache\n\
     Write: tokens stored in prompt cache for future requests\n\
     Depending on provider, cache tokens may overlap with input tokens"
}

/// Concise token semantics help text for analytics and detail views.
pub fn token_semantics_help_tooltip() -> &'static str {
    "Input: tokens sent to the model\n\
     Output: tokens generated by the model\n\
     Reasoning: extra reasoning tokens when the assistant reports them\n\
     Cache: cache activity; depending on provider, cache tokens may overlap with input tokens"
}

/// Format a session duration in seconds as a compact human-readable string.
///
/// - `< 60s` → `"< 1m"`
/// - `< 1h`  → `"Nm"`
/// - `≥ 1h`  → `"Nh Mm"` (minutes omitted when 0)
pub fn format_session_duration(seconds: i64) -> String {
    if seconds < 60 {
        "< 1m".to_string()
    } else if seconds < 3600 {
        format!("{}m", seconds / 60)
    } else {
        let hours = seconds / 3600;
        let minutes = (seconds % 3600) / 60;
        if minutes == 0 {
            format!("{}h", hours)
        } else {
            format!("{}h {}m", hours, minutes)
        }
    }
}

/// Return the dominant activity string using the design precedence:
/// edits > commands > reads > messages.
pub fn format_dominant_activity(
    edit_count: usize,
    command_count: usize,
    read_count: usize,
    message_count: usize,
) -> String {
    if edit_count > 0 {
        pluralize(edit_count, "edit", "edits")
    } else if command_count > 0 {
        pluralize(command_count, "command", "commands")
    } else if read_count > 0 {
        pluralize(read_count, "read", "reads")
    } else {
        pluralize(message_count, "message", "messages")
    }
}

fn pluralize(count: usize, singular: &str, plural: &str) -> String {
    if count == 1 {
        format!("1 {singular}")
    } else {
        format!("{count} {plural}")
    }
}

/// Map a stored ending_status to its UI display label.
/// Returns `None` for `"clean"` and `"unknown"` (hidden in the UI).
pub fn ending_label(status: &str) -> Option<&'static str> {
    match status {
        "abrupt" => Some("interrupted"),
        "error" => Some("failed"),
        _ => None,
    }
}

/// CSS class for a session ending label.
pub fn ending_css_class(status: &str) -> &'static str {
    match status {
        "clean" => "ending-completed",
        "abrupt" => "ending-interrupted",
        "error" => "ending-failed",
        _ => "ending-unknown",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::TokenUsage;

    #[test]
    fn format_token_count_zero() {
        assert_eq!(format_token_count(0), "0");
    }

    #[test]
    fn format_token_count_under_thousand() {
        assert_eq!(format_token_count(999), "999");
    }

    #[test]
    fn format_token_count_thousands() {
        assert_eq!(format_token_count(1000), "1\u{2009}000");
        assert_eq!(format_token_count(12345), "12\u{2009}345");
    }

    #[test]
    fn format_token_count_millions() {
        assert_eq!(format_token_count(1234567), "1\u{2009}234\u{2009}567");
    }

    #[test]
    fn format_token_count_negative() {
        assert_eq!(format_token_count(-1234), "-1\u{2009}234");
    }

    #[test]
    fn format_token_details_input_output_only() {
        let usage = TokenUsage {
            input_tokens: 12345,
            output_tokens: 678,
            cache_read_tokens: None,
            cache_write_tokens: None,
            reasoning_tokens: None,
        };
        assert_eq!(
            format_token_details(&usage),
            "12\u{2009}345 input \u{00b7} 678 output"
        );
    }

    #[test]
    fn format_token_details_with_reasoning() {
        let usage = TokenUsage {
            input_tokens: 12345,
            output_tokens: 678,
            cache_read_tokens: None,
            cache_write_tokens: None,
            reasoning_tokens: Some(456),
        };
        assert_eq!(
            format_token_details(&usage),
            "12\u{2009}345 input \u{00b7} 678 output \u{00b7} 456 reasoning"
        );
    }

    #[test]
    fn format_token_cache_both() {
        let usage = TokenUsage {
            input_tokens: 0,
            output_tokens: 0,
            cache_read_tokens: Some(9012),
            cache_write_tokens: Some(234),
            reasoning_tokens: None,
        };
        assert_eq!(
            format_token_cache(&usage),
            Some("9\u{2009}012 read \u{00b7} 234 write".to_string())
        );
    }

    #[test]
    fn format_token_cache_read_only() {
        let usage = TokenUsage {
            input_tokens: 0,
            output_tokens: 0,
            cache_read_tokens: Some(200),
            cache_write_tokens: None,
            reasoning_tokens: None,
        };
        assert_eq!(format_token_cache(&usage), Some("200 read".to_string()));
    }

    #[test]
    fn format_token_cache_none() {
        let usage = TokenUsage {
            input_tokens: 100,
            output_tokens: 50,
            cache_read_tokens: None,
            cache_write_tokens: None,
            reasoning_tokens: None,
        };
        assert_eq!(format_token_cache(&usage), None);
    }

    #[test]
    fn token_details_tooltip_without_reasoning() {
        let usage = TokenUsage {
            input_tokens: 100,
            output_tokens: 50,
            cache_read_tokens: None,
            cache_write_tokens: None,
            reasoning_tokens: None,
        };
        let tooltip = token_details_tooltip(&usage);
        assert!(tooltip.contains("Input:"));
        assert!(tooltip.contains("Output:"));
        assert!(!tooltip.contains("Reasoning:"));
    }

    #[test]
    fn token_details_tooltip_with_reasoning() {
        let usage = TokenUsage {
            input_tokens: 100,
            output_tokens: 50,
            cache_read_tokens: None,
            cache_write_tokens: None,
            reasoning_tokens: Some(30),
        };
        let tooltip = token_details_tooltip(&usage);
        assert!(tooltip.contains("Reasoning:"));
    }

    #[test]
    fn format_analytics_token_primary_formats_input_output_total() {
        assert_eq!(
            format_analytics_token_primary(12345, 678),
            "12\u{2009}345 input / 678 output / 13\u{2009}023 total"
        );
    }

    #[test]
    fn format_analytics_token_secondary_returns_none_without_optional_data() {
        assert_eq!(format_analytics_token_secondary(None, None, None), None,);
    }

    #[test]
    fn format_analytics_token_secondary_supports_cache_and_reasoning() {
        assert_eq!(
            format_analytics_token_secondary(Some(9012), Some(234), Some(56)),
            Some("cache: 9\u{2009}012 read \u{00b7} 234 write \u{00b7} reasoning: 56".to_string()),
        );
    }

    #[test]
    fn token_semantics_help_mentions_provider_overlap() {
        let tooltip = token_semantics_help_tooltip();
        assert!(tooltip.contains("Input:"));
        assert!(tooltip.contains("Output:"));
        assert!(tooltip.contains("Reasoning:"));
        assert!(tooltip.contains("cache"));
        assert!(tooltip.contains("provider"));
        assert!(tooltip.contains("overlap"));
    }

    #[test]
    fn token_cache_tooltip_mentions_possible_overlap_with_input() {
        let tooltip = token_cache_tooltip();
        assert!(tooltip.contains("cache"));
        assert!(tooltip.contains("input"));
        assert!(tooltip.contains("overlap"));
    }

    #[test]
    fn format_session_duration_under_a_minute() {
        assert_eq!(format_session_duration(0), "< 1m");
        assert_eq!(format_session_duration(30), "< 1m");
        assert_eq!(format_session_duration(59), "< 1m");
    }

    #[test]
    fn format_session_duration_minutes() {
        assert_eq!(format_session_duration(60), "1m");
        assert_eq!(format_session_duration(90), "1m");
        assert_eq!(format_session_duration(300), "5m");
        assert_eq!(format_session_duration(2700), "45m");
    }

    #[test]
    fn format_session_duration_hours() {
        assert_eq!(format_session_duration(3600), "1h");
        assert_eq!(format_session_duration(5400), "1h 30m");
        assert_eq!(format_session_duration(7200), "2h");
    }

    #[test]
    fn format_dominant_activity_edits_first() {
        assert_eq!(format_dominant_activity(3, 2, 1, 10), "3 edits");
        assert_eq!(format_dominant_activity(1, 2, 1, 10), "1 edit");
    }

    #[test]
    fn format_dominant_activity_commands_when_no_edits() {
        assert_eq!(format_dominant_activity(0, 5, 3, 10), "5 commands");
        assert_eq!(format_dominant_activity(0, 1, 3, 10), "1 command");
    }

    #[test]
    fn format_dominant_activity_reads_when_no_edits_or_commands() {
        assert_eq!(format_dominant_activity(0, 0, 4, 10), "4 reads");
        assert_eq!(format_dominant_activity(0, 0, 1, 10), "1 read");
    }

    #[test]
    fn format_dominant_activity_messages_as_fallback() {
        assert_eq!(format_dominant_activity(0, 0, 0, 10), "10 messages");
        assert_eq!(format_dominant_activity(0, 0, 0, 1), "1 message");
    }

    #[test]
    fn ending_label_maps_status_to_display_text() {
        assert_eq!(ending_label("clean"), None);
        assert_eq!(ending_label("abrupt"), Some("interrupted"));
        assert_eq!(ending_label("error"), Some("failed"));
        assert_eq!(ending_label("unknown"), None);
        assert_eq!(ending_label(""), None);
    }

    #[test]
    fn ending_css_class_maps_status_to_class() {
        assert_eq!(ending_css_class("clean"), "ending-completed");
        assert_eq!(ending_css_class("abrupt"), "ending-interrupted");
        assert_eq!(ending_css_class("error"), "ending-failed");
        assert_eq!(ending_css_class("unknown"), "ending-unknown");
    }
}
